name: Build and Push Docker Images to Container Registry

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  IMAGE_NAME: storage-account-app
  REGISTRY_NAME: devacrshared1.azurecr.io
  TAG_NAME: latest

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2.7.0
      
    - name: Set up pack CLI
      run: |
        curl -sSL "https://github.com/buildpacks/pack/releases/download/v0.28.0/pack-v0.28.0-linux.tgz" | sudo tar -C /usr/local/bin/ --no-same-owner -xzv pack
        
    - name: Login to Container Registry
      uses: docker/login-action@v2.1.0
      with:
        registry: ${{ env.REGISTRY_NAME }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
        
    - name: Build and push Spring Boot app
      run: |
        pack build ${{ env.REGISTRY_NAME }}/${{ env.IMAGE_NAME }}:${{ env.TAG_NAME }} \
          --path ./apps/storage-account-app/ \
          --builder paketobuildpacks/builder:base \
          --publish
        
    - name: Logout of Container Registry
      run: docker logout ${{ env.REGISTRY_NAME }}
