name: Deploy with Terraform

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0
        
    - name: Login to Azure
      run: az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
      env:
        AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Initialize Terraform
      run: terraform init ContainerAppsJavaDemo/environments/dev/storage-account-app

    - name: Validate Terraform configuration
      run: terraform validate ContainerAppsJavaDemo/environments/dev/storage-account-app

    - name: Plan Terraform deployment
      run: terraform plan -out=tfplan ContainerAppsJavaDemo/environments/dev/storage-account-app
